[[headers]]
for = "*"
[headers.values]
Access-Control-Allow-Origin = "https://withamscouts.org.uk"
Content-Security-Policy = "default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self' data: https:; connect-src 'self' data: blob:; font-src 'self' data:; manifest-src 'self';"
Expect-CT = "max-age=86400, enforce"
Permissions-Policy = "accelerometer=(), autoplay=(), camera=(), cross-origin-isolated=(), document-domain=(), encrypted-media=(self), fullscreen=(), geolocation=(self), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=()"
Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "0"
# URL shortners
[[redirects]]
from = "/3rd-waiting-list"
status = 302
to = "https://www.onlinescoutmanager.co.uk/waiting-list/3rd-witham-3rd-witham-waiting-list/e2693ec5-8323-4dd0-98ac-9b77c22b1fb5/apply"
[[redirects]]
from = "/uniform"
status = 302
to = "https://shop.scouts.org.uk/journal/2022/06/20/badge-placement-2"
# App proxy
[[redirects]]
from = "/*"
status = 200
to = "/index.html"
